"""Followed players: a career README and one README per season for a player the user follows but does not control
(the user's request, October 2026: Chris Bosh).

Read-only projections of canonical records, rebuilt with the player reports. Each player in
`foundation/followed_players.json` gets `career/<folder>/README.md` (every season) and `career/<folder>/<season>/README.md`:
- identity from the league player registry; club and number on the career date (`league_cards.club_on`, `jerseys.number_for`);
- regular-season and playoff lines from closed game results only (`write_back.closed_results`,
  `playoff_stats.closed_playoff_results`), with his club's record and playoff exit;
- honors from the league's recorded award decisions, only once announced on or before the career date, and his FIBA
  team medals from the closed tournaments' medal registers (`national_medals.medals_for`, by NBA id, from the close,
  or by a medal's dated link to his registry row from the link date);
- season highs and milestones with his age on the day (`runtime/stat_milestones.py`);
- the user's target line for a season (`targets` in his `player.json`) against the closed games;
- which ability model the engine used for him that season: his real career, or (an alternate-history player,
  `trajectories.ALTERNATE_FROM`) his own expected profile.

Nothing here changes the player. His club's front office decides his moves; the engine decides his games.
"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = Path("foundation/followed_players.json")
LEAGUE = Path("career/Dwyane_Wade/Stats_and_Awards/League")
GENERATED = "<!-- Generated by scripts/update_player_reports.py from closed results and award records; do not edit. -->\n"
HEADERS = ["Season", "Age", "Team", "GP/GS", "MPG", "PPG", "RPG", "APG", "SPG", "BPG", "FG%", "3P%", "FT%", "TS% (est.)", "Team result"]


def _read(path):
    path = Path(path)
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else None


def followed(root=ROOT):
    data = _read(Path(root) / CONFIG)
    return data["players"] if data else []


def _registry(root, bbr):
    data = _read(Path(root) / LEAGUE / "player_registry.json") or {"players": []}
    players = data["players"] if isinstance(data, dict) else data
    return next((p for p in players if p.get("bbr_id") == bbr), None)


def games(root, name, season, as_of):
    """The player's closed regular-season and playoff game records in the season, in date order."""
    from .playoff_stats import closed_playoff_results
    from .write_back import closed_results, game_records
    out = []
    for competition, rows in (("regular", closed_results(root, season, as_of)), ("playoff", closed_playoff_results(root, season, as_of))):
        for row in rows:
            for _side, pid, _bbr, record in game_records(row, root, season):
                if pid == name and record.get("line"):
                    out.append(dict(record, competition=competition))
    return sorted(out, key=lambda r: (r["date"], r["event_id"]))


def honors(root, name, season, as_of):
    """[(announced, honor)] the league's records give the player for the season, announced by the career date, each
    decision as it stood on that date (`award_corrections.as_of`: a later correction is not read before its date)."""
    from .award_corrections import as_of as known_on
    out, base = [], Path(root) / LEAGUE / season
    for d in (_read(base / "season_awards.json") or {}).get("decisions", []):
        if d.get("announced_on", "9999") > as_of:
            continue
        d = known_on(d, as_of)
        if name in (d.get("winners") or []):
            out.append((d["announced_on"], d["name"]))
        for team in d.get("teams") or []:
            if any(p.get("player") == name for p in team.get("players", [])):
                out.append((d["announced_on"], f"{d['name'].rstrip('s')}: {team['team']}"))
    for a in (_read(base / "all_star.json") or {}).get("all_stars", []):
        if a.get("player") == name and a.get("selected_on", "9999") <= as_of:
            out.append((a["selected_on"], f"All-Star ({a.get('conference')}, {a.get('role')})"))
    for d in (_read(base / "award_decisions.json") or {}).get("decisions", []):
        d = known_on(d, as_of)
        if d.get("winner") == name and d.get("announced_on", "9999") <= as_of:
            out.append((d["announced_on"], f"{d.get('conference', '')} {d['name']} ({d['period_start']} to {d['period_end']})".strip()))
    return sorted(out)


def medal_honor_rows(root, bbr, as_of, page_dir):
    """[[edition, awarded, honor]] for the player's FIBA team medals awarded on or before the career date (a medal won
    under his FIBA identity once its dated link holds, `national_medals.links`), each linked to the tournament page's
    medal table (`runtime/national_medals.py`)."""
    from .national_medals import honor_text, link, medals_for
    return [[f"{m['edition']} FIBA", m["awarded_on"], f"[{honor_text(m)}]({link(m, page_dir, root)})"]
            for m in medals_for(bbr_id=bbr, on=as_of, root=root)]


def team_result(root, club, season, as_of):
    from .seasons import dates
    from .standings import standings_on
    try:
        row = standings_on(min(as_of, dates(season, root)["regular_season_end"]), root, season).get(club)
    except (OSError, KeyError, ValueError):
        row = None
    text = f"{row['wins']}-{row['losses']}" if row else "no games yet"
    series = [s for s in (_read(Path(root) / LEAGUE / season / "playoffs.json") or {}).get("series", [])
              if club in s.get("clubs", []) and s.get("winner")]
    if series:
        last = series[-1]
        text += f" · {'won' if last['winner'] == club else 'lost'} {last.get('round', '').replace('_', ' ')}"
    return text


def _pct(x):
    return "N/A" if x is None else f"{100 * x:.1f}"


def _n(x):
    return "N/A" if x is None else f"{x:.1f}"


def _row(season, age, club, a, extra):
    if not a["gp"]:
        return [season, age, club, "0", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", extra]
    pg = a["pg"]
    return [season, age, club, f"{a['gp']}/{a['gs']}", _n(pg["minutes"]), _n(pg["pts"]), _n(pg["reb"]), _n(pg["ast"]), _n(pg["stl"]),
            _n(pg["blk"]), _pct(a["rates"]["fg_pct"]), _pct(a["rates"]["three_pct"]), _pct(a["rates"]["ft_pct"]),
            _pct(a["rates"]["ts_pct"]), extra]


def _table(headers, rows, empty="None yet."):
    if not rows:
        return empty + "\n"
    return ("| " + " | ".join(headers) + " |\n| " + " | ".join("---" for _ in headers) + " |\n"
            + "".join("| " + " | ".join(str(c) for c in r) + " |\n" for r in rows))


def _highs(regular):
    rows = []
    for key, label in (("pts", "Points"), ("reb", "Rebounds"), ("ast", "Assists"), ("stl", "Steals"), ("blk", "Blocks"),
                       ("tpm", "Threes"), ("ftm", "Free throws")):
        top = max((g["line"].get(key) or 0) for g in regular)
        first = next(g for g in regular if (g["line"].get(key) or 0) == top)
        ties = sum(1 for g in regular if (g["line"].get(key) or 0) == top) - 1
        rows.append([label, top, f"{first['date']} {'vs' if first.get('venue') == 'home' else 'at'} {first['opponent']}"
                     + (f" (+{ties})" if ties else "")])
    return rows


def _season_end(root, season):
    from .seasons import dates
    return dates(season, root)["regular_season_end"]


def _model(entry, season):
    from .trajectories import alternate
    if alternate(entry["bbr_id"], season):
        return (f"Alternate history (the user's premise): his own expected profile for {season} "
                f"([expected_profile.json](expected_profile.json): previous expectation, his simulated season, the age step and "
                f"the user's development profile), with the engine's journaled season swing.")
    return "His real career's rates for the season (the talent-trajectory exception), with the engine's journaled swing."


def _targets(entry, season, regular):
    from .career_stats import aggregate
    t = (entry.get("targets") or {}).get(season)
    if not t:
        return ""
    a = aggregate(regular)
    actual = (lambda k: _n(a["pg"]["minutes"] if k == "mpg" else a["pg"][k])) if a["gp"] else (lambda k: "—")
    rate = (lambda k: _pct(a["rates"][k])) if a["gp"] else (lambda k: "—")
    rows = [[label, f"{t[k]:.1f}", actual(k)] for k, label in (("mpg", "Minutes"), ("pts", "Points"), ("reb", "Rebounds"),
                                                                 ("ast", "Assists"), ("stl", "Steals"), ("blk", "Blocks")) if k in t]
    rows += [[label, f"{100 * t[k]:.1f}", rate(k)] for k, label in (("fg_pct", "FG%"), ("three_pct", "3P%"), ("ft_pct", "FT%"),
                                                                    ("ts_pct", "TS% (est.)")) if k in t]
    return (f"## The user's target line against the closed games\n\nTargets from {t.get('source', 'the development profile')}; "
            f"actual from {a['gp']} closed regular-season games.\n\n" + _table(["Per game", "Target", "Actual"], rows) + "\n")


def build(root=ROOT, as_of=None):
    """{path: text} for every followed player's career and season READMEs, as of the career date."""
    from .career_stats import aggregate
    from .jerseys import number_for
    from .league_cards import club_on
    from .seasons import live_seasons, state
    from .stat_milestones import age_on, age_text, career_milestones, markdown as milestones_markdown
    from .career_dashboard import career_overview, season_highs
    from .league_cards import COLORS_FILE, club_colors
    root = Path(root)
    entries = followed(root)
    if not entries:
        return {}
    as_of = as_of or state(None, root)["current_date"]
    seasons = live_seasons(root)
    outputs = {}
    for entry in entries:
        reg = _registry(root, entry["bbr_id"]) or {}
        name, birth = entry.get("name") or reg.get("name"), reg.get("birth_date")
        folder = root / "career" / entry["folder"]
        club = (club_on(reg, as_of, root=root) or {}).get("club") or reg.get("team_name")
        number = number_for(entry["bbr_id"], club, root) if club else None
        rel = lambda page, target: os.path.relpath(target, page.parent).replace(os.sep, "/")
        colors = json.loads((root / COLORS_FILE).read_text(encoding="utf-8")) if (root / COLORS_FILE).is_file() else None

        def palette(season, club=club):
            if not colors:
                return None
            c = club_colors(club, int(season[:4]), colors)
            return {"primary": c["primary"], "light": "#e6dcf5"}

        def identity(season, club=club, number=number):
            snap = {"as_of": "2003-06-26", "full_name": entry.get("full_name") or name, "display_name": name,
                    "team": club or "Free agent", "league": "NBA", "positions": [reg.get("position", "PF")], "jersey": number,
                    "height_in_shoes": entry.get("height", "N/A"), "weight_lb": entry.get("weight_lb", "N/A"),
                    "physical_profile_as_of": entry.get("measured_on", "N/A"), "entry": entry.get("draft") or "N/A",
                    "roster_status": f"{club}, real player followed (not controlled)", "prior_program": entry.get("college") or "N/A"}
            return {"date_of_birth": birth, "snapshots": [snap]}
        head = (f"Career date: **{as_of}** · {club or 'No club'} · #{number or 'N/A'} · {reg.get('position', 'N/A')} · "
                f"age {age_on(birth, as_of)[0] if birth else 'N/A'}\n\n")
        all_games, reg_rows, po_rows, honor_rows = [], [], [], []
        for season in seasons:
            lines = games(root, name, season, as_of)
            all_games += lines
            regular = [g for g in lines if g["competition"] == "regular"]
            playoff = [g for g in lines if g["competition"] == "playoff"]
            teams = sorted({g["team"] for g in regular}) or [club]
            s_age = str(age_on(birth, season[:4] + "-11-01")[0]) if birth else "N/A"
            result = " / ".join(team_result(root, t, season, as_of) for t in teams if t)
            page = folder / season / "README.md"
            row = _row(f"[{season}]({season}/README.md)", s_age, " / ".join(t or "N/A" for t in teams), aggregate(regular), result)
            reg_rows.append(row)
            if playoff:
                po_rows.append(_row(season, s_age, playoff[0]["team"], aggregate(playoff), team_result(root, playoff[0]["team"], season, as_of)))
            season_honors = [[day, h] for day, h in honors(root, name, season, as_of)]
            honor_rows += [[season, *h] for h in season_honors]
            data = career_milestones(all_games, birth)
            in_season = [[r["milestone"], r["date"], r["age"], r["opponent"]] for r in data["regular"] + data["playoff"] + data["firsts"]
                         if r.get("season") == season]
            card = folder / "assets" / f"season_overview_{season}.svg"
            outputs[card] = career_overview(identity(season), min(as_of, _season_end(root, season)), aggregate(regular),
                                            aggregate(playoff), season_highs(lines, season) if regular else [],
                                            f"{season} regular-season highs", season=season, palette=palette(season))
            text = GENERATED + f"\n# {name} | {season} season\n\n" + f"![{name} {season} season overview]({rel(page, card)})\n\n" + head
            text += f"[Career]({rel(page, folder / 'README.md')})"
            if entry.get("profile"):
                text += f" · [Development profile (user-supplied)]({rel(page, folder / entry['profile'])})"
            text += f" · [League card]({rel(page, root / LEAGUE / 'Players' / (entry['bbr_id'] + '.md'))})\n\n"
            text += f"**Ability model this season:** {_model(entry, season)}\n\n"
            text += "## Regular season\n\n" + _table(HEADERS, [_row(season, s_age, row[2], aggregate(regular), result)]) + "\n"
            text += _targets(entry, season, regular)
            text += "## Playoffs\n\n" + (_table(HEADERS, [_row(season, s_age, playoff[0]["team"], aggregate(playoff), team_result(root, playoff[0]["team"], season, as_of))])
                                         if playoff else "No playoff games closed.\n") + "\n"
            text += "## Season highs (regular season)\n\n" + (_table(["Stat", "High", "Game"], _highs(regular)) if regular else "No games closed.\n") + "\n"
            text += "## Honors\n\n" + _table(["Announced", "Honor"], season_honors, "No recorded honors this season.") + "\n"
            text += "## Milestones this season\n\n" + _table(["Milestone", "Date", "Age", "Opponent"], sorted(in_season, key=lambda r: r[1]),
                                                             "None this season.") + "\n"
            outputs[page] = text
        data = career_milestones(all_games, birth)
        career = folder / "README.md"
        current = max((g["season"] for g in all_games if g["competition"] == "regular"), default=None)
        card = folder / "assets" / "career_overview.svg"
        outputs[card] = career_overview(identity(seasons[-1]), as_of, aggregate([g for g in all_games if g["competition"] == "regular"]),
                                        aggregate([g for g in all_games if g["competition"] == "playoff"]),
                                        season_highs(all_games, current) if current else [],
                                        f"{current} regular-season highs" if current else "Season highs", palette=palette(seasons[-1]))
        milestones_page = folder / "career_milestones.md"
        outputs[milestones_page] = GENERATED + "\n" + milestones_markdown(name, birth, as_of, data,
            lambda note: rel(milestones_page, root / note) if note else "").replace(
            "[Season tracker](calendar.md) · [All milestones](README.md)", "[Career](README.md)")
        text = GENERATED + f"\n# {name} | Career\n\n" + f"![{name} career overview](assets/career_overview.svg)\n\n" + head
        text += ("A real player the user follows, not one the user controls: his club decides his moves and the engine plays his "
                 "games. Every number below comes from closed simulated games and the league's recorded award decisions.\n\n")
        if entry.get("profile"):
            text += f"[Development profile (user-supplied)]({entry['profile']}) · "
        text += (f"[League card]({rel(career, root / LEAGUE / 'Players' / (entry['bbr_id'] + '.md'))}) · "
                 f"[Career milestones](career_milestones.md) · Seasons: "
                 + " · ".join(f"[{s_}]({s_}/README.md)" for s_ in seasons) + "\n\n")
        ident = [["Full name", entry.get("full_name") or name], ["Born", birth or "N/A"], ["Hometown", entry.get("hometown") or "N/A"],
                 ["College", entry.get("college") or "N/A"], ["Draft", entry.get("draft") or "N/A"], ["Position", reg.get("position", "N/A")],
                 ["Club on the career date", club or "N/A"], ["Number", number or "N/A"]]
        text += "## Identity\n\n" + _table(["Field", "Value"], ident) + "\n"
        text += "## Regular season by season\n\n" + _table(HEADERS, reg_rows) + "\n"
        text += "## Playoffs\n\n" + _table(HEADERS, po_rows, "No playoff games closed.") + "\n"
        medal_rows = medal_honor_rows(root, entry["bbr_id"], as_of, career.parent)
        if medal_rows:                                   # by award date; league rows keep their order
            honor_rows = sorted(honor_rows + medal_rows, key=lambda r: r[1])
        text += "## Honors\n\n" + _table(["Season", "Announced", "Honor"], honor_rows, "No recorded honors yet.") + "\n"
        firsts = [[r["milestone"], r["date"], r["age"], r["season"], r["opponent"], r["line"]] for r in data["firsts"]]
        text += "## Career firsts\n\n" + _table(["Milestone", "Date", "Age", "Season", "Opponent", "Line"], firsts) + "\n"
        reached = [[r["milestone"], r["date"], r["age"], r["season"], r["game_number"], r["opponent"]] for r in data["regular"] + data["playoff"]]
        text += "## Milestones reached\n\n" + _table(["Milestone", "Date", "Age", "Season", "Game no.", "Opponent"], reached) + "\n"
        nxt = [[r["milestone"], f"{r['current']:,}", f"{r['needed']:,}"] for r in data["regular_next"]]
        text += "## Next milestones\n\n" + _table(["Milestone", "Current", "Still needed"], nxt) + "\n"
        outputs[career] = text
    return outputs
