"""Not-started statistics and award pages for a new season (the rollover, roadmap 18).

Every league, Miami and award page the in-season writers rewrite in place (`write_back.statistics_pages`,
`award_decisions.render_pages`) must exist before the season's first game. This module writes them for a season's
calendar (`seasons.month_weeks`): the season page, a page for each month and each week, at the same paths and in the
same layout as the previous season's, empty of results. The static text (position tables of registry players,
coverage notes, usage rules) is taken from the previous season's page at the same level, where only the season in
links changes; the period-specific parts (title, links, dates, period tables, neighbours) are built here. Each page
is then passed once through its own rewriter, so it is exactly what the writer would produce with no closed game.

Wade's own report pages are generated by `runtime/player_reports.py` from the same calendar.
"""
from __future__ import annotations

import calendar as cal
from datetime import date
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
STATS = Path("career/Dwyane_Wade/Stats_and_Awards")


def _long(day):
    d = date.fromisoformat(day)
    return f"{d.strftime('%B')} {d.day}, {d.year}"


class Calendar:
    """The season's months and weeks with their labels and date ranges."""

    def __init__(self, season, root=ROOT):
        from .seasons import month_weeks
        self.season = season
        self.months = [(name, m, y, folder, weeks) for name, m, y, folder, weeks in month_weeks(season, root)]

    def month_label(self, month):
        name, m, y, folder, weeks = month
        return f"{name} {y}"

    def month_dates(self, month):
        name, m, y, folder, weeks = month
        return f"{name} 1-{cal.monthrange(y, m)[1]}, {y}"

    def week_dates(self, month, week):
        name, m, y, folder, weeks = month
        last = cal.monthrange(y, m)[1]
        lo, hi = 1 + (week - 1) * 7, (week * 7 if week < 4 else last)
        return f"{name} {lo}-{hi}, {y}"

    def weeks(self):
        """[(month, week)] in calendar order."""
        return [(month, w) for month in self.months for w in month[4]]


def _section(text, start, stop):
    """The text from the line starting `start` up to (not including) the line starting `stop`."""
    i = text.index(start)
    j = text.index(stop, i + len(start))
    return text[i:j]


def _swap_season(text, old, new):
    return text.replace(f"/{old}/", f"/{new}/").replace(f"{old}/", f"{new}/")


def _period_table(rows, kind):
    head = "| Period | Calendar dates | Closed games | Status |" if kind == "games" else "| Period | Calendar dates | Closed decisions | Status |"
    status = "Not started" if kind == "games" else "No award filed"
    return "\n".join([head, "| --- | --- | ---: | --- |"] + [f"| [{label}]({link}) | {dates} | 0 | {status} |" for label, link, dates in rows]) + "\n"


def _neighbours(prev, nxt, word, page):
    parts = []
    if prev:
        parts.append(f"[Previous {word}]({prev}/{page})")
    if nxt:
        parts.append(f"[Next {word}]({nxt}/{page})")
    return " · ".join(parts)


class Builder:
    def __init__(self, season, root=ROOT):
        from .seasons import previous_season
        self.root, self.season = Path(root), season
        self.prev = previous_season(season)
        self.cal = Calendar(season, root)
        self.base = self.root / STATS

    # -- shared pieces ------------------------------------------------------------------------
    def _template(self, kind, level):
        """The previous season's page of a kind at a level (season, month or week)."""
        folder = {"league": "League", "team": "Team", "awards": "League"}[kind]
        name = {"league": "League_Stats.md", "team": "Team_Stats.md", "awards": "League_Awards.md"}[kind]
        root = self.base / folder / self.prev
        if level == "season":
            path = root / name
        elif level == "month":
            path = next(p for p in sorted(root.glob(f"*/{name}")) if p.parent.name[:2] == "12")
        else:
            path = next(p for p in sorted(root.glob(f"*/Week_2/{name}")) if p.parent.parent.name[:2] == "12")
        return _swap_season(path.read_text(encoding="utf-8"), self.prev, self.season)

    def _month_neighbours(self, i):
        months = self.cal.months
        prev = f"../{months[i - 1][3]}" if i > 0 else None
        nxt = f"../{months[i + 1][3]}" if i + 1 < len(months) else None
        return prev, nxt

    def _week_neighbours(self, month, week):
        weeks = self.cal.weeks()
        k = weeks.index((month, week))

        def rel(pair):
            m, w = pair
            return f"../Week_{w}" if m is month else f"../../{m[3]}/Week_{w}"
        return (rel(weeks[k - 1]) if k > 0 else None), (rel(weeks[k + 1]) if k + 1 < len(weeks) else None)

    # -- League_Stats ----------------------------------------------------------------------------
    def league(self, level, month=None, week=None, i=None):
        s = self.season
        tpl = self._template("league", level)
        positions = _section(tpl, "## Players by position", "## By " if level != "week" else "## Coverage")
        coverage = tpl[tpl.index("## Coverage"):]
        coverage = coverage.split("\n\n[Previous")[0].split("\n\n[Next")[0].rstrip() + "\n"
        tracked = re.search(r"^(\d+) tracked players", tpl, re.M).group(1)
        if level == "season":
            head = (f"# NBA players | {s}\n\n[Stats hub](../../README.md) · [Wade](../../{s}/README.md) · "
                    f"[Miami](../../Team/{s}/Team_Stats.md) · [NBA awards](League_Awards.md)\n\nNBA regular season · {s}\n\n")
            period = "## By month\n\n" + _period_table([(self.cal.month_label(m), f"{m[3]}/League_Stats.md", self.cal.month_dates(m)) for m in self.cal.months], "games") + "\n"
            nav = ""
        elif level == "month":
            label = self.cal.month_label(month)
            head = (f"# NBA players | {label}\n\n[Stats hub](../../../README.md) · [Season](../League_Stats.md) · "
                    f"[Wade](../../../{s}/{month[3]}/README.md) · [Miami](../../../Team/{s}/{month[3]}/Team_Stats.md) · "
                    f"[NBA awards](League_Awards.md)\n\nNBA regular season · {self.cal.month_dates(month)}\n\n")
            period = "## By week\n\n" + _period_table([(f"Week {w}", f"Week_{w}/League_Stats.md", self.cal.week_dates(month, w)) for w in month[4]], "games") + "\n"
            nav = _neighbours(*self._month_neighbours(i), "month", "League_Stats.md")
        else:
            label = self.cal.month_label(month)
            head = (f"# NBA players | {label} | Week {week}\n\n[Stats hub](../../../../README.md) · [{label}](../League_Stats.md) · "
                    f"[Wade](../../../../{s}/{month[3]}/Week_{week}/README.md) · [Miami](../../../../Team/{s}/{month[3]}/Week_{week}/Team_Stats.md) · "
                    f"[NBA awards](League_Awards.md)\n\nNBA regular season · {self.cal.week_dates(month, week)}\n\n")
            period = ""
            nav = _neighbours(*self._week_neighbours(month, week), "week", "League_Stats.md")
        from .write_back import NO_LEADERS
        text = (head + f"{tracked} tracked players · 0 closed games in this record · Not started.\n\n## Leaders\n\n{NO_LEADERS}\n\n"
                + positions.rstrip() + "\n\n" + period + coverage + (f"\n{nav}\n" if nav else ""))
        return text

    # -- Team_Stats ------------------------------------------------------------------------------
    def team(self, level, month=None, week=None, i=None):
        s = self.season
        tpl = self._template("team", level)
        body = _section(tpl, "## Team record", "## By " if level != "week" else "Departures retain")
        body = re.sub(r"\n<details>\n<summary>Team-control status and player cards</summary>.*?</details>\n", "\n", body, flags=re.S)
        tail = tpl[tpl.index("Departures retain"):]
        tail = tail.split("\n\n[Previous")[0].split("\n\n[Next")[0].rstrip() + "\n"
        if level == "season":
            head = (f"# Miami Heat | {s}\n\n[Stats hub](../../README.md) · [Wade](../../{s}/README.md) · "
                    f"[NBA players](../../League/{s}/League_Stats.md) · [NBA awards](../../League/{s}/League_Awards.md)\n\nNBA regular season · {s}\n\n")
            period = ("## By month\n\n" + _period_table([(self.cal.month_label(m), f"{m[3]}/Team_Stats.md", self.cal.month_dates(m)) for m in self.cal.months], "games")
                      + "\n## Playoffs\n\nNo playoff games recorded. Use a separate playoff ledger; do not add postseason games to the regular-season totals.\n\n")
            nav = ""
        elif level == "month":
            label = self.cal.month_label(month)
            head = (f"# Miami Heat | {label}\n\n[Stats hub](../../../README.md) · [Season](../Team_Stats.md) · "
                    f"[Wade](../../../{s}/{month[3]}/README.md) · [NBA players](../../../League/{s}/{month[3]}/League_Stats.md) · "
                    f"[NBA awards](../../../League/{s}/{month[3]}/League_Awards.md)\n\nNBA regular season · {self.cal.month_dates(month)}\n\n")
            period = "## By week\n\n" + _period_table([(f"Week {w}", f"Week_{w}/Team_Stats.md", self.cal.week_dates(month, w)) for w in month[4]], "games") + "\n"
            nav = _neighbours(*self._month_neighbours(i), "month", "Team_Stats.md")
        else:
            label = self.cal.month_label(month)
            head = (f"# Miami Heat | {label} | Week {week}\n\n[Stats hub](../../../../README.md) · [{label}](../Team_Stats.md) · "
                    f"[Wade](../../../../{s}/{month[3]}/Week_{week}/README.md) · [NBA players](../../../../League/{s}/{month[3]}/Week_{week}/League_Stats.md) · "
                    f"[NBA awards](../../../../League/{s}/{month[3]}/Week_{week}/League_Awards.md)\n\nNBA regular season · {self.cal.week_dates(month, week)}\n\n")
            period = ""
            nav = _neighbours(*self._week_neighbours(month, week), "week", "Team_Stats.md")
            tail = re.sub(r"\[Game records\]\([^)]*\)", f"[Game records](../../../../../{s}/06_Regular_Season/{month[3]}/Week_{week}/note.md)", tail)
        status = "As of N/A: not started.\n\n"
        return head + status + body.rstrip() + "\n\n" + period + tail + (f"\n{nav}\n" if nav else "")

    # -- League_Awards ---------------------------------------------------------------------------
    def awards(self, level, month=None, week=None, i=None, clock=None):
        s = self.season
        if level == "season":
            tpl = self._template("awards", "season")
            text = re.sub(r"^As of [^\n]*$", f"As of {_long(clock)}: no award decisions closed.", tpl, count=1, flags=re.M)
            text = re.sub(r"^## By month\n\n.*?\n\n", lambda _: "## By month\n\n" + _period_table(
                [(self.cal.month_label(m), f"{m[3]}/League_Awards.md", self.cal.month_dates(m)) for m in self.cal.months], "decisions") + "\n",
                text, count=1, flags=re.M | re.S)
            return text
        from .award_decisions import _section as award_section, conference_names
        confs = conference_names(s, self.root)
        intro = ("Official award window: not recorded. Announcement date: not recorded.\n\n"
                 "The rows below are an internal shortlist, not published NBA vote totals. A calendar bucket can contain no award "
                 "decision; file a decision where its official period ends.\n\n")
        status = f"As of {_long(clock)}: no award decisions closed.\n\n"
        if level == "month":
            label = self.cal.month_label(month)
            head = (f"# NBA awards | {label}\n\n[Stats hub](../../../README.md) · [Season](../League_Awards.md) · "
                    f"[Wade](../../../{s}/{month[3]}/README.md) · [Miami](../../../Team/{s}/{month[3]}/Team_Stats.md) · "
                    f"[NBA players](League_Stats.md)\n\n{s} · Calendar coverage: {self.cal.month_dates(month)}\n\n")
            sections = award_section("Player of the Month", [], clock, confs) + award_section("Rookie of the Month", [], clock, confs)
            by_week = "## By week\n\n" + _period_table([(f"Week {w}", f"Week_{w}/League_Awards.md", self.cal.week_dates(month, w)) for w in month[4]], "decisions")
            nav = _neighbours(*self._month_neighbours(i), "month", "League_Awards.md")
            tail = f"\n[Awards procedure and research](../../README.md) · [Player evidence for this calendar period](League_Stats.md)\n"
        else:
            label = self.cal.month_label(month)
            head = (f"# NBA awards | {label} | Week {week}\n\n[Stats hub](../../../../README.md) · [{label}](../League_Awards.md) · "
                    f"[Wade](../../../../{s}/{month[3]}/Week_{week}/README.md) · [Miami](../../../../Team/{s}/{month[3]}/Week_{week}/Team_Stats.md) · "
                    f"[NBA players](League_Stats.md)\n\n{s} · Calendar coverage: {self.cal.week_dates(month, week)}\n\n")
            sections = award_section("Player of the Week", [], clock, confs)
            by_week = ""
            nav = _neighbours(*self._week_neighbours(month, week), "week", "League_Awards.md")
            tail = f"\n[Awards procedure and research](../../../README.md) · [Player evidence for this calendar period](League_Stats.md)\n"
        record = "## Decision record\n\nNo award decision is filed in this calendar bucket yet.\n"
        return (head + status + intro + "\n".join(sections) + "\n" + record + ("\n" + by_week if by_week else "")
                + tail + (f"\n{nav}\n" if nav else ""))

    # -- all pages -------------------------------------------------------------------------------
    def pages(self, clock):
        """{path: text} for every page of the season."""
        out = {}
        for kind, folder, name in (("league", "League", "League_Stats.md"), ("team", "Team", "Team_Stats.md"), ("awards", "League", "League_Awards.md")):
            build = getattr(self, kind)
            extra = {"clock": clock} if kind == "awards" else {}
            root = self.base / folder / self.season
            out[root / name] = build("season", **extra)
            for i, month in enumerate(self.cal.months):
                out[root / month[3] / name] = build("month", month=month, i=i, **extra)
                for w in month[4]:
                    out[root / month[3] / f"Week_{w}" / name] = build("week", month=month, week=w, **extra)
        return out


def write(season, clock, root=ROOT):
    """Write every not-started page that does not exist yet, then pass each through its rewriter. Returns the paths."""
    root = Path(root)
    written = []
    for path, text in Builder(season, root).pages(clock).items():
        if path.is_file():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    from .write_back import write_statistics_pages
    write_statistics_pages(root, season)
    return written
